Primjer grupe iz resursa:

<?xml version="1.0" encoding="Windows-1250"?>
<grupaStudenata idgrupe="3678">
<brojGrupe>1</brojGrupe>
<ime>DEB</ime>
<opis></opis>
<predmet isvuid="149737" semestar="1">Energetska učinkovitost</predmet>
<studenti brojStudenata="34">
<student>
<jmbag>0165043258</jmbag>
<ime>Ivan</ime>
<prezime>Arambašić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054302</jmbag>
<ime>Matej</ime>
<prezime>Arić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0246046127</jmbag>
<ime>Ivan</ime>
<prezime>Bančić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054440</jmbag>
<ime>Tomislav</ime>
<prezime>Čabrajac</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165051251</jmbag>
<ime>Ivan</ime>
<prezime>Čurčić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054461</jmbag>
<ime>Martina</ime>
<prezime>Ćurić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054498</jmbag>
<ime>Stjepan</ime>
<prezime>Duspara</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054568</jmbag>
<ime>Kristijan</ime>
<prezime>Hanžek</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054589</jmbag>
<ime>Petar</ime>
<prezime>Huis</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165051379</jmbag>
<ime>Dario</ime>
<prezime>Ivančević</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054594</jmbag>
<ime>Filip</ime>
<prezime>Jakupec</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054601</jmbag>
<ime>Darko</ime>
<prezime>Jakus</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165051428</jmbag>
<ime>Ivana</ime>
<prezime>Josipović</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165052446</jmbag>
<ime>Mihael</ime>
<prezime>Kaučić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054690</jmbag>
<ime>Josip</ime>
<prezime>Klinc</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054729</jmbag>
<ime>Marija</ime>
<prezime>Kovačević</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054760</jmbag>
<ime>Damir</ime>
<prezime>Krancpiler</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054776</jmbag>
<ime>Mario</ime>
<prezime>Krešo</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0314002596</jmbag>
<ime>Marcel</ime>
<prezime>Leder</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054888</jmbag>
<ime>Josip</ime>
<prezime>Maskaljević</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165055016</jmbag>
<ime>Ivan</ime>
<prezime>Nikolić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165055037</jmbag>
<ime>Nikolina</ime>
<prezime>Orlović</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165055058</jmbag>
<ime>Hrvoje</ime>
<prezime>Palčić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165055149</jmbag>
<ime>Tomislav</ime>
<prezime>Pirić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165055203</jmbag>
<ime>Nedjeljko</ime>
<prezime>Rado</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0036468464</jmbag>
<ime>Filip</ime>
<prezime>Relić</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165051678</jmbag>
<ime>Danijel</ime>
<prezime>Šalković</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165055411</jmbag>
<ime>Antonela</ime>
<prezime>Vidović</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165054045</jmbag>
<ime>Nikolina</ime>
<prezime>Zovko</prezime>
<redovni>1</redovni>
</student>
<student>
<jmbag>0165022894</jmbag>
<ime>Ivica</ime>
<prezime>Čabraja</prezime>
<redovni>3</redovni>
</student>
<student>
<jmbag>0149011968</jmbag>
<ime>Damir</ime>
<prezime>Hanzer</prezime>
<redovni>3</redovni>
</student>
<student>
<jmbag>0165020538</jmbag>
<ime>Ivan</ime>
<prezime>Ličanin</prezime>
<redovni>3</redovni>
</student>
<student>
<jmbag>0165020522</jmbag>
<ime>Ivan</ime>
<prezime>Pućo</prezime>
<redovni>3</redovni>
</student>
<student>
<jmbag>0165042133</jmbag>
<ime>Robert</ime>
<prezime>Štrangar</prezime>
<redovni>3</redovni>
</student>
</studenti>
</grupaStudenata>